parent = "core/debian-bookworm"

recipes = [
    "core/debian-grub-setup",
    "core/ssh",
    "debian-setup-network",
    "debian-setup-timesyncd",
    "_mender-config",
    "_install-test-keys",
    "_rugix-system-assert",
]

[parameters."core/pkg-cleanup"]
autoremove = true
