#!/bin/bash

set -euo pipefail

STATE="$1"
FILES="$2"

case "$STATE" in
    ArtifactInstall)
        IMG=$(find "${FILES}" -name "*.img" -type f -print -quit)
        mkdir -p /run/rugix/data/mender
        rugix-ctrl system commit >/run/rugix/data/mender/update.log 2>&1
        rugix-ctrl update install --no-reboot "${IMG}" >>/run/rugix/data/mender/update.log 2>&1
        touch /run/rugix/.mender-reboot-spare
        ;;
    NeedsArtifactReboot)
        echo "Automatic"
        ;;
    ArtifactVerifyReboot)
        spare=$(rugix-ctrl system info | grep Spare | xargs | awk '{print $2}')
        hot=$(rugix-ctrl system info | grep Hot | xargs | awk '{print $2}')
        if [ "${spare}" != "${hot}" ]; then
            # The spare partition should be the hot one after a successful update.
            exit 1;
        fi
        ;;
    ArtifactCommit)
        mkdir -p /run/rugix/data/mender
        rugix-ctrl system commit >/run/rugix/data/mender/commit.log 2>&1
        ;;
esac

exit 0